### ISSUE TITLE
Add simple auth using ENV and an object inside res.body

### ISSUE THREAD

**Issue by upperwal** [DataSpace-Mobility/data-standard-registry-doc#10]

**Comment by groverHarshit** [comment]
Fixed under [e708dc2338efab15556c6f5cbe3ab4342b246339](https://github.com/groverHarshit/data-standard-registry-doc/commit/e708dc2338efab15556c6f5cbe3ab4342b246339)

**Comment by upperwal** [comment]
Resolved under #7
