### ISSUE TITLE
Create getLatestByShortName function

### ISSUE THREAD

**Issue by upperwal** [DataSpace-Mobility/data-standard-registry-doc#11]

**Comment by groverHarshit** [comment]
Done under Commit [f5658f20af5fc5181fa4eff90b16f081d07d3a41](https://github.com/groverHarshit/data-standard-registry-doc/commit/f5658f20af5fc5181fa4eff90b16f081d07d3a41)

**Comment by upperwal** [comment]
Resolved under #7
