### ISSUE TITLE
Create an endpoint for getLatestByUUID

### ISSUE THREAD

**Issue by upperwal** [DataSpace-Mobility/data-standard-registry-doc#12]

**Comment by groverHarshit** [comment]
Done under commit [6e52d4a13382830b888a1d6caa3912d0d9d2d44a](https://github.com/groverHarshit/data-standard-registry-doc/commit/6e52d4a13382830b888a1d6caa3912d0d9d2d44a)

**Comment by upperwal** [comment]
Resolved under #7
