### ISSUE TITLE
create an endpoint for getAllVersionsByShortName

### ISSUE THREAD

**Issue by upperwal** [DataSpace-Mobility/data-standard-registry-doc#13]

**Comment by groverHarshit** [comment]
Done under commit [176f4a02f1347c7451da040f5a0eac55b270ca5b](https://github.com/groverHarshit/data-standard-registry-doc/commit/176f4a02f1347c7451da040f5a0eac55b270ca5b)

**Comment by upperwal** [comment]
Resolved under #7
