### ISSUE TITLE
create an endpoint for getStandardByUUID

### ISSUE THREAD

**Issue by upperwal** [DataSpace-Mobility/data-standard-registry-doc#14]

**Comment by groverHarshit** [comment]
Done under commit [044ef0c6bc50a61d62b44c7e7d091ba469a34a3b](https://github.com/groverHarshit/data-standard-registry-doc/commit/044ef0c6bc50a61d62b44c7e7d091ba469a34a3b)

**Comment by upperwal** [comment]
Resolved under #7
