### ISSUE TITLE
Create a update version method and change schema for version.

### ISSUE THREAD

**Issue by groverHarshit** [DataSpace-Mobility/data-standard-registry-doc#16]
Added major, minor and patch in version schema.
Added function for update in version.
Done under commit [b4661fa8726d7740ef51a8afe9ca5deed1ebe3ff](https://github.com/groverHarshit/data-standard-registry-doc/commit/b4661fa8726d7740ef51a8afe9ca5deed1ebe3ff)

**Comment by upperwal** [comment]
Resolved under #7
