### ISSUE TITLE
Check for duplicate entry before create

### ISSUE THREAD

**Issue by upperwal** [DataSpace-Mobility/data-standard-registry-doc#9]
https://github.com/DataSpace-Mobility/data-standard-registry-doc/blob/5a211e2d3430719a9c385f1060e62737d83ffd35/api/controllers/standard/standard.controller.js#L4-L6

`res.body` will have the same structure as the standard.model without `uuid`, `versions.uuid` and `versions.version`.

Check against `info.short_name` for duplicate entry before inserting in the DB.

**Comment by groverHarshit** [comment]
Resolved under commit ID [248b9485faf494b26ccc7842b7830ad495c5b97c](https://github.com/groverHarshit/data-standard-registry-doc/commit/248b9485faf494b26ccc7842b7830ad495c5b97c)

**Comment by upperwal** [comment]
Resolved under #7
